[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pypreroms"
authors = [{name = "Gorka Solana Arteche", email = "gorsol@gmail.com"}]
dynamic = ["version", "description"]
